### ISSUE TITLE
Error loading Extension?

### ISSUE THREAD

**Issue by Argo11** [Corbeno/Idleon-Api-Downloader#1]
So I'm running into this issue when trying to use the Extension. I'm assuming this is why its not giving me any link, because it's failing to create them in the first place. 

![image](https://user-images.githubusercontent.com/41308765/123981958-4b7a0680-d988-11eb-998a-ed65d733d9b5.png)

**Comment by Corbeno** [comment]
I'm looking into this now. It looks like some things changed in the latest update. Thank you for your patience

**Comment by Corbeno** [comment]
It looks like the issue was caused by missing Maestro data. Is one of your characters by chance the Maestro class? 

I just pushed a fix, please let me know if you are still running into issues. Thanks!

**Comment by Argo11** [comment]
Update has fixed the issue. Thank you!
